### ISSUE TITLE
Unable to join LAN server

### ISSUE THREAD

**Issue by YinRyka** [ssblur/scriptor#102]
**Forge version**: 49.0.19
**Minecraft version**: 1.20.4
The mod load fine on the host computer but anyone who tries to join the LAN gets this code.
**Error code after attempt on joining.**: 
Internal Exception: io.netty.handler.codec.DecoderException: Not a compound tag: 168296449

All mods are the same, (The only mod on the server is this mod and its dependency) I have tried to reinstall the forge version, mods, and other recommendations from the internet that is related to this code. Nothing worked.

**Log file**
[latest.log](https://github.com/ssblur/scriptor/files/13928902/latest.log)

**Comment by ssblur** [comment]
Thank you for reporting! I know you said you both had it installed, but based on this log, it would appear you do not have Scriptor installed. You will need to have the same version of Scriptor installed as the person hosting in order to connect. Can you install Scriptor and try connecting again? 

Thank you again!

**Comment by ssblur** [comment]
Was able to replicate the issue using the public release on Forge 1.20.4 thanks to a secondary report, working on a solution.

**Comment by ssblur** [comment]
The latest version, 1.0.7, should fix this issue. Downloads will be available on CurseForge and Modrinth shortly. Thank you again for reporting!
