### ISSUE TITLE
[bug] enhancing weapon spells do not work

### ISSUE THREAD

**Issue by NihoDoMesa** [ssblur/scriptor#42]
**Mod Version (e.g. Fabric 0.3.4)**:
Forge 43.2.0

**What you expect to happen**:
The Sword or Bow is enchanted for any duration of time, with the aspect defined in the spellbook e.g. lightning in the case of the Charge weapon spell provided by the mod.

**What actually happens**:
The spell provided by the mod is to strong for a book as it simply fizzels out, however a self made spell that used fire as aspect would not exceed the book limit. That spell was still unable to enchant any item. An attemt with a simpler Lightning aspect has not been made. The game is modded. A list of the additional mods will be provided.

One may be able to reproduce the bug by using any spell book with the item/enchanting target on an item in the inventory.

Mod list:

Animal Feeding Trough             ver 1.0.3+1.19.2-forge
AppleSkin                                 ver 2.4.2+mc1.19
Architectury                              ver 6.3.69
ChickenChunks                        ver 2.9.4.97
CodeChicken Lib                      ver 4.3.0.470
Comforts                                 ver 6.0.3+1.19.2
Create                                     ver 0.5.0.h
Create Enchantment Industry  ver 1.1.12
Create Ore Excavation              ver 0.3.2
Create: Steam 'n Rails               ver 1.19.2-1.1.1
Giacomo's bookshelves Mod    ver 1.3.3
Just Enough Items                   ver 11.4.0.287
Map Atlases                             ver 3.0.1
Moonlight Library                   ver 1.19.2-2.1.14
Scriptor                                   ver 0.3.5
Storage Drawers                     ver 11.1.2
Supplementaries                     ver 1.19.2-2.2.26
Terralith                                  ver 1.0

[scriptor_dictionary.zip](https://github.com/ssblur/scriptor/files/11297550/scriptor_dictionary.zip)

**Comment by ssblur** [comment]
I'm sorry, I am unable to replicate this issue. When using the "Charge Weapon" spell on an item using your dictionary data, the Charged II enchantment is added as expected. This spell will fail when used in your hand, however. Using an Identify Scroll on this item will reveal how to use this item (by picking it up with your cursor and right clicking on the target item in your inventory).

The fire action, when cast through imbue, will not enchant items. This is intentional. It does have another effect when cast on items in your inventory.

How are you casting this spell, and if you are using it as intended, can you tell me precisely which message you are seeing, if any?

**Comment by ssblur** [comment]
I don't know why I didn't think about this, but this was not implemented yet in creative due to the way it handles the player's inventory. This has been implemented, and will work in future versions.

Thank you for reporting.
