### ISSUE TITLE
[bug] Few bugs and errors (1.20.4)

### ISSUE THREAD

**Issue by kingkuys2123** [ssblur/scriptor#92]
## **Mod Version (e.g. Fabric 0.3.4)**:

Minecraft 1.20.4
Fabric 0.15.3
Fabric API 0.91.3
Java 20.0.2
Scriptor 1.0.4

## **ISSUES**:
 1. [Parsing errors loading custom advancements shows up in the logs upon loading a world.](https://pastebin.com/mzVw1DWY)

 2. A Warning shows up in the log saying missing textures `[20:35:50] [Worker-ResourceReload-3/WARN]: Missing textures in model scriptor:light#: minecraft:textures/atlas/blocks.png:scriptor:entity/empty_circle`
 
 3. Missing break particles for chalk circles, runes and magic light
![2023-12-31_20 55 26](https://github.com/ssblur/scriptor/assets/114457180/b036e2e8-118a-47a6-bee2-dc9311730399)
 
 4. You can place chalk circles on chalk circles (also with runes), unless this is intentional. Additionally chalks stays in the air or float when there is no block below it, the chalk should break if there is no block below it.
![2023-12-31_20 56 58](https://github.com/ssblur/scriptor/assets/114457180/538d7ef7-1b52-4681-91fb-7fb83b9b74f0)

 5. Apparently, you can place chalk down without looking at the block, I can't explain it so heres a video:

https://github.com/ssblur/scriptor/assets/114457180/fdc36051-5bb2-4894-990e-0070b21da1d9

## SUGGESTIONS
 1. A restriction where players can't place chalk or chalk circles unless they bind it with a spell through anvil
 2. Add a durability for chalk

**Comment by ssblur** [comment]
Thank you for reporting these issues! The fourth item is intentional, and the fifth item is a consequence of the vanilla trace function, so while I will look into it I may not be able to resolve it elegantly at the moment.

I will look into the first item and can resolve the second and third items promptly. I'll update this ticket once these are all addressed, though it may be a few days as I'm still busy with the holidays.

If you run into any new issues in the meantime, please feel free to open additional tickets. Thank you again for reporting!

**Comment by ssblur** [comment]
Hey, found some time to sort this sooner than expected. Working on a few other minor changes before the next minor version, so these fixes will be rolled into that update. Thank you again for reporting, please let me know if you continue to have issues with 1-3 after upgrading to 1.0.5

**Comment by kingkuys2123** [comment]
Sweet, thanks :)
